const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const aiService = require('../../../bot/utils/aiService');

module.exports = {
  name: "ask",
  category: "ai",
  description: "Ask Jack AI a question",
  usage: "/ask <prompt>",

  data: new SlashCommandBuilder()
    .setName("ask")
    .setDescription("Ask Jack AI a question")
    .addStringOption(o => o.setName("prompt").setDescription("What do you want to ask?").setRequired(true)),

  async run(ctx) {
    const prompt = ctx.options.getString("prompt");

    // Defer the reply because AI takes time
    await ctx.interaction.deferReply();

    try {
      const response = await aiService.generateResponse(prompt);

      // Discord has a 2000 character limit for content
      if (response.length > 2000) {
        const embed = new EmbedBuilder()
          .setTitle("🤖 Jack AI Response")
          .setColor("Gold")
          .setDescription(response.slice(0, 4000)) // Embed limit is higher (4096)
          .setFooter({ text: "Generated by Gemini 1.5 Flash" })
          .setTimestamp();
          
        return ctx.interaction.editReply({ embeds: [embed] });
      }

      await ctx.interaction.editReply({ content: response });

    } catch (err) {
      console.error('[AICommand] Error:', err.message);
      await ctx.interaction.editReply({ content: "❌ Failed to generate a response. Please try again later." });
    }
  }
};
